# Generated by Django 4.0.5 on 2022-06-26 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Категория')),
                ('content', models.TextField(verbose_name='Описание категории')),
                ('image', models.ImageField(blank=True, upload_to='images/', verbose_name='Основное изображение для категории')),
            ],
        ),
    ]
