# Generated by Django 4.0.5 on 2022-06-26 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0002_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
    ]
