# Generated by Django 4.0.5 on 2022-06-27 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0004_additionalimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalimage',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additionalImg', to='api_app.category', verbose_name='Категория'),
        ),
    ]
