# Generated by Django 4.0.5 on 2022-06-28 12:06

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0005_alter_additionalimage_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(verbose_name='№ аппартаментов')),
                ('price', models.PositiveSmallIntegerField(verbose_name='Цена')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='number_category', to='api_app.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Номер',
                'verbose_name_plural': 'Номера',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrival_date', models.DateField(verbose_name='Дата заезда')),
                ('departure_date', models.DateField(verbose_name='Дата отъезда')),
                ('adult', models.PositiveSmallIntegerField(verbose_name='Количество взрослых')),
                ('childeren', models.PositiveSmallIntegerField(verbose_name='Количество детей')),
                ('child_age', models.CharField(max_length=100, verbose_name='Возраст детей')),
                ('client_name', models.CharField(max_length=100, verbose_name='Имя клиента')),
                ('phone', models.CharField(max_length=12, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 10 digits allowed.", regex='^((\\+7)+([0-9]){10})$')], verbose_name='Телефон покупателя')),
                ('agreement', models.BooleanField(verbose_name='согласие на обработку данных')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_room', to='api_app.room', verbose_name='Номер')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
    ]
