# Generated by Django 4.0.5 on 2022-06-29 08:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0006_room_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='done',
            field=models.BooleanField(default=False, verbose_name='Заказ исполнен'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='paid',
            field=models.BooleanField(default=False, verbose_name='Заказ оплачен'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.CharField(max_length=12, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+79998882255'. Up to 10 digits allowed.", regex='^((\\+7)+([0-9]){10})$')], verbose_name='Телефон покупателя'),
        ),
    ]
