# Generated by Django 4.0.5 on 2022-06-30 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0008_order_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='days',
            field=models.IntegerField(blank=True),
        ),
    ]
