# Generated by Django 4.0.5 on 2022-06-30 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0009_alter_order_days'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='days',
        ),
    ]
