# Generated by Django 4.0.5 on 2022-06-30 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0011_remove_room_price_category_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeasonRatio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Начало')),
                ('end_date', models.DateField(verbose_name='Конец')),
                ('ratio', models.DecimalField(decimal_places=2, max_digits=3, verbose_name='Коэффициент')),
            ],
            options={
                'verbose_name': 'Сезонный коэффициент',
                'verbose_name_plural': 'Сезонные коэффициенты',
            },
        ),
    ]
